language: java
sudo: false
install: true
jdk:
- oraclejdk13
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
script: "./gradlew test"
deploy:
  provider: heroku
  api_key:
    secure: mvlrNzntKs+861Otnbb4bB0oalFjofYeTz+D/KQy/QzZb8CRGlHZ3ZsXr8VulGzcIRCAWcx92QVm1rNrwzbdIemLZkQMST21vDrEEJN9qaxBK8HGnYzmzAaijI3MsNmpCvqOMltDAIlUX/vajjXARnRx/ALobcglzvf1tVLHcVK9yXtSgHOXR7S+9qWhjOagqn5y2gbs+0/2kmzdI73RQKInRvId5rI6AtW0S5eJafFdQHNnXMm6okeoeqdId1wjOfZwvz8x/azfUNPC7IeYNBniUi4MYYpiv5QN13yt2NkmWOFAtPk4Zmnte8R414iZlL1PQGNwt3S9ptCYO26TdQ9gr5rZ/dvSHkoQ5sQjamrbCTJAZzZM4rM+zFUzoK5qiue6S99wMeDOfpZSrnmTTrQYHkD/4E9ouV8UTqB7Bsz48UquZiZFo6axQYnjXttt1mkOaFuoho9FrztUfgYeA/rZ9owSXgg5hCDK1/6BWYPThF5RONJqvxiokCaQ5LzxZKypItAhPjVnQgA237CqqynlnQjung8epLZN3LUAMQJPHrtApIkIgsrShTlCiTyoy61nep24NIC7R1nTOb2OkF8MCPTy3yJQvCGRSEraIitE4X/KaxckYR7f4Xppe2f7v4JkSTaJ4gkMKwWcuJOjJHGSoU93JaV8x2pmCPpsAtc=
  app: not-enough-tg-bots
  on:
    repo: Senderman/not-enough-tg-bots
